### ISSUE TITLE
Compile error using 'Release with Code Analysis' configuration

### ISSUE THREAD

**Issue by micdenny** [dotnetprojects/WpfToolkit#10]
![compile-error-release-with-codeanalysis](https://cloud.githubusercontent.com/assets/1633595/5008159/435d9344-6a5a-11e4-94b2-ddf651ff2912.png)

**Comment by jogibear9988** [comment]
This Property exists only in NET 4.5, but we compile for 4.0

**Comment by micdenny** [comment]
> This Property exists only in NET 4.5, but we compile for 4.0

so what we have to do with that release compilation?

**Comment by jogibear9988** [comment]
don't know why its there, its already in the original project

**Comment by micdenny** [comment]
ok then, we can close this issue as "by design" :smile:
