### ISSUE TITLE
ExpandableContentControl has zero size

### ISSUE THREAD

**Issue by Torvin** [dotnetprojects/WpfToolkit#16]
This sample XAML won't render anything at all.
```xaml
<Window x:Class="Test.Window1"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:primitives="clr-namespace:System.Windows.Controls.Primitives;assembly=DotNetProjects.Layout.Toolkit"
        Title="Window1" Height="300" Width="300">
    <Grid>
        <primitives:ExpandableContentControl Percentage="1" RevealMode="Right">
            <Button>123</Button>
        </primitives:ExpandableContentControl>
    </Grid>
</Window>
```
This is because `ExpandableContentControl` calculates its size before the content gets measured and thus ends up with zero size.
The only way I could make it work - to set `RevealMode` in `OnLoaded` event. This helps, since content is measured by that time.

**Comment by jogibear9988** [comment]
I've found this: https://social.msdn.microsoft.com/Forums/silverlight/en-US/525a8a14-7b93-4ce3-8e4d-72ce1552d8f0/accordionitem-content-resize-at-runtime?forum=silverlightcontrols

But it seems it got never fixed. I'll look after it when I've time

**Comment by Torvin** [comment]
Actually I've completely rewritten `ExpandableContentControl` now, but my version neither supports Silverlight nor works with current `Accordion` implementation...

**Comment by jogibear9988** [comment]
maybe you can share your code?

**Comment by Torvin** [comment]
Sure. I'm not sure if it is useful for you, but here it is: https://gist.github.com/Torvin/686f3b3d8d15af854018

This version is based on the original code, but:
* It doesn't support Silverlight (I've just deleted the code for Silverlight as I don't need it, sorry)
* Doesn't change its `Width` or `Height` properties (honestly, that was a really weird way to do the expansion...). Instead it properly handles `MeasureOverride`/`ArrangeOverride` to achieve the same effect.
* Clients don't have to animate `Percentage` property. The control will animate it itself, upon setting its `IsExpanded` property
* Previously the size of the child wasn't properly set during animation (when `Percentage < 1`). So, for example child `WrapPanel` behaved incorrectly. This is no longer the case.
* I couldn't make it work with current implementation of `Accordion`. I don't use `Accordion` so I didn't try too hard.

**Comment by jogibear9988** [comment]
On mor question, whats the difference from Expander to this control (if not yet used it!)

**Comment by Torvin** [comment]
You mean the standard [`Expander`](https://msdn.microsoft.com/en-us/library/system.windows.controls.expander%28v=vs.110%29.aspx)? Standard one has an arrow and a header (so it is a `HeaderedContentControl`) and is not animated. 

While this control only does animation of expansion/collapse of its child, and no additional elements like arrows or headers are rendered.

**Comment by jogibear9988** [comment]
Should be fixed by using your Control Torvin.

Thanks for the contribution
