### ISSUE TITLE
Demo of AutoCompleteComboBox possibly broken

### ISSUE THREAD

**Issue by buckleyGI** [dotnetprojects/WpfToolkit#20]
Or I don't understand the purpose.

http://screencast.com/t/aMHmT8xrLnYY

The selections isn't narrowed down to items containing "Calendar" and I can't interact with the API combobox. Its set to disabled but what is the purpose then?

I saw this at work and thought it was a fluke. At home I see the same behavior. Both systems are VS 2015 Update 2 and targeting .NET 4.5

Before I can fix it I should know if this is normal behavior :)

**Comment by jogibear9988** [comment]
Look at the Example after my changes
