### ISSUE TITLE
ExpandableContentControl does not resize on content resize

### ISSUE THREAD

**Issue by gpomykala** [dotnetprojects/WpfToolkit#21]
ContentSite's size remains fixed even if the content had been resized - to be specific, ContentSite's ActualHeight remains fixed even in nested StackPanel's ActualHeight grows. How ContentPresenter's size is determined?

Example markup below:

`        <controls:AccordionItem Header="item1" HorizontalAlignment="Stretch" HorizontalContentAlignment="Stretch">
            <StackPanel HorizontalAlignment="Stretch">
                <Grid HorizontalAlignment="Stretch">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition />
                        <ColumnDefinition />
                    </Grid.ColumnDefinitions>
                    <Label Grid.Column="0" Grid.Row="0" Content="name"  />
                    <TextBox Grid.Column="1" Grid.Row="0" Text="title" />
                </Grid>
                <DockPanel>
                    <Button x:Name="button" Height="100" Width="200" Click="Button_OnClick">Grow Up</Button>
                </DockPanel>
            </StackPanel>
        </controls:AccordionItem>`

**Comment by jogibear9988** [comment]
should be fixed

**Comment by gpomykala** [comment]
Thanks for a comprehensive fix. That was quick!
