### ISSUE TITLE
Control of LineSeries legend entry visibility

### ISSUE THREAD

**Issue by cdokolas** [dotnetprojects/WpfToolkit#24]
At this time, changing the visibility of a `LineSeries` object controls only its visibility in the graph (e.g. if the line is shown or not). This should also be reflected in the legend (i.e. the corresponding legend item should correspondingly be shown or not).

**Comment by jogibear9988** [comment]
I'll look for it

**Comment by jogibear9988** [comment]
Should be fixed in Newest Version
