### ISSUE TITLE
How to use label in piechart

### ISSUE THREAD

**Issue by Kanimozhi12** [dotnetprojects/WpfToolkit#28]
Hi,

Recently I have gone through this. https://github.com/dotnetprojects/WpfToolkit/blob/master/WpfToolkit/DataVisualization/Charting/Series/LabeledPieSeries.cs .

and i have created a pieseries of type labeledpieseries. But i dont know how to enable label with that. I want to display a label with piechart .

![capture4](https://cloud.githubusercontent.com/assets/17586319/23792742/529fd03c-05ae-11e7-9560-ca0e1ef9d6f3.PNG)

Is that possible with this Labeled pieSeries

**Comment by jogibear9988** [comment]
Sorry don't know if this is possible. Have you already solved it?

**Comment by jogibear9988** [comment]
no answer
