### ISSUE TITLE
Multiple values with delimiter in AutoComplete textbox

### ISSUE THREAD

**Issue by Shinigamae** [dotnetprojects/WpfToolkit#29]
Hi there,

The WPFToolkit works quite well. I wonder if we can change it somehow to allow multiple values insertion like "apple, pineapple, strawberry" with suggestion after every new delimiter ("," in this case) is input.

I don't use GitHub much so I'm not sure if this is a right way to post suggestion/question. Please let me know if this's not appropriate.

Thanks,
Shinigamae

**Comment by jogibear9988** [comment]
maybe the TokenizedTextBox of https://github.com/dotnetprojects/WpfExtendedToolkit is something in that direction?

**Comment by jogibear9988** [comment]
No answer till now, closeing
