### ISSUE TITLE
Search string text not being updated after item is selected. 

### ISSUE THREAD

**Issue by rplant** [dotnetprojects/WpfToolkit#30]
After modifying the search string. ( ex. Changing Main Street N to just Main Street ) and then selecting an item like "Main Street S" from the dropdown. 

The correct item is in SelectItem, but the Search Street remains "Main Street".

This only happens when SelectedItem is bound.

**Comment by jogibear9988** [comment]
Where? In AutoCompleteBox? Does this work now?

**Comment by jogibear9988** [comment]
closed cause of no answer
