### ISSUE TITLE
just want to know the difference with https://github.com/xceedsoftware/wpftoolkit

### ISSUE THREAD

**Issue by LeiYangGH** [dotnetprojects/WpfToolkit#31]
Hi Men,

Both the 2 projects are named wpftoolkit so it is a bit confusing.
Is there any compassion?
Maybe this area is not appropriate to ask such kind of question, but i really need some explanations.

**Comment by jogibear9988** [comment]
This project is a fork of https://wpf.codeplex.com/ the WPF Toolkit from Microsoft. Xceeds Wpf Toolkit is Named "Extended WPF Toolkit" from wich I have also a fork at: https://github.com/dotnetprojects/WpfExtendedToolkit because Xceed fixed some errors very slow
