### ISSUE TITLE
AutoCompleteBox - SearchText does not clear if SelectedItem=null

### ISSUE THREAD

**Issue by djux66** [dotnetprojects/WpfToolkit#33]
SearchText property of AutoCompleteBox doesnt clear if I set SelectedItem == null.
Can you fix this? 
Tried to bind Text to some property on ViewModel and then set that to string.Empty but it doesnt work.

**Comment by jogibear9988** [comment]
No, it's not alawys the case that Text should be cleard if I clear the item. Maybe your binding was not TowWay?

**Comment by AceCoderLaura** [comment]
It's true that it may not be every use case, but there should probably be a flag on the control to enable it.

I worked around it by handling the SelectionChanged event.
```cs
    private void AutoCompleteBox_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        var box = (System.Windows.Controls.AutoCompleteBox)sender;
        if (box.SelectedItem == null) box.Text = null;
    }
```

I tried a couple different approaches from the view model, but they were all stupidly hacky. Doing it in the codebehind was the most straightforward option.
