### ISSUE TITLE
Cannot clone WpfToolkit in VS 2019 because global.json points to old SDK version

### ISSUE THREAD

**Issue by PeterHuberSg** [dotnetprojects/WpfToolkit#42]
I tried to clone WpfToolkit from Visual Studio 2019 Verson 16.4.1

I get some files, but in the solution explorer is says it could not load all the projects:
![image](https://user-images.githubusercontent.com/49078578/71704772-4bdb2500-2e17-11ea-9dee-4946849a1345.png)

When I try to reload a project, I get the error message:
_Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version._

I have  installed:
![image](https://user-images.githubusercontent.com/49078578/71705039-7a0d3480-2e18-11ea-8560-8ab43b7618fe.png)

WpfToolkit\WpfToolkit\global.json:
`{
  "sdk": {
    "version": "3.0.100-preview8"
  }
}`

When I removed global.json, everthing worked fine.

I guess you should remove global.json as well ? If you cannot do that, at least in the read me file you should explain what one has to do that he can clone WpfToolkit successfully.

**Comment by jogibear9988** [comment]
i‘ve created it before netcore 3 was final,
need to fix that 

Von meinem iPhone gesendet

**Comment by PeterHuberSg** [comment]
I have another strange problem:
![image](https://user-images.githubusercontent.com/49078578/71724153-3216fd80-2e6a-11ea-98f7-6d6ac638a4af.png)

In WPFToolkitSamples, AutoCompleteBoxSample.xaml I get these Error messages like "The member XXX is not accessible ...", but it compiles and runs just fine. Maybe a VS bug ?

**Comment by jogibear9988** [comment]
Don't know... If it compiles and works it seems so...
Maybe you need to ask in a MS Repo...

**Comment by jogibear9988** [comment]
fixed in last version
