### ISSUE TITLE
AutoCompleteBox's LostFocus Event triggers when clicking on its Popup items

### ISSUE THREAD

**Issue by Saliom** [dotnetprojects/WpfToolkit#47]
It works perfectly fine with keyboard selection, but if you try to select an item from the Popup list with a mouse click, it will trigger the AutoCompleteBox's LostFocus Event twice, while the control still has focus in the end.

Very simple steps to reproduce :
- Listen to an AutoCompleteBox's LostFocus Event
- Click on one of its Popup items

**Comment by micdenny** [comment]
as a workaround I can suggest to use [reactive](https://github.com/dotnet/reactive) and apply a [buffer](http://reactivex.io/documentation/operators/buffer.html) or a [debounce](http://reactivex.io/documentation/operators/debounce.html) or if you can distinct by some data you can use a [distinct](http://reactivex.io/documentation/operators/distinct.html)

in the meanwhile if you have an idea on how we can fix this problem from the source code I would encourage you to open a pull request

thank you

**Comment by Saliom** [comment]
Not sure if this can be fixed, since it does happen as well on basic controls like ComboBoxes. A solution I found to filter those misleading Events is to check if KeyBoardFocus is still within the control on LostFocus like the following: 

```csharp
private void AutoCompleteBox_LostFocus(object sender, RoutedEventArgs e)
{
    if (!(sender as Control).IsKeyboardFocusWithin)
    { 
        // The Control truly lost focus
    }
}
```

**Comment by micdenny** [comment]
> Not sure if this can be fixed, since it does happen as well on basic controls like ComboBoxes

so I would close the issue, because I think we should not block something that is coming from the under framework.

BTW I think I pointed you out what is a good practice to do with events in general, reactive it's designed a lot for that.

**Comment by Saliom** [comment]
> BTW I think I pointed you out what is a good practice to do with events in general, reactive it's designed a lot for that.

I checked the filters you pointed out in the previous comment, but unfortunately none of them seemed to fit for this particular situation. The simple [Filter](http://reactivex.io/documentation/operators/filter.html) filter could probably do the trick with the `IsKeyboardFocusWithin` condition, but it's already possible to do that filtering without Reactive, so unless there's a speed difference or some information about Reactive I don't know yet, It doesn't seem necessary in this case.

**Comment by micdenny** [comment]
> but it's already possible to do that filtering without Reactive, so unless there's a speed difference or some information about Reactive I don't know yet, It doesn't seem necessary in this case.

in your case you're right, stick on the simplest way, reactive gain a lot when you have a stream of events, and you want a finer control over it
