### ISSUE TITLE
How to start in readme

### ISSUE THREAD

**Issue by CarlosAdrianM** [dotnetprojects/WpfToolkit#52]
I think it would be very useful to add a "how to" in the readme file. I am trying to remove old Xceed toolkit and use this one, but I am not able.

I have opened this ticket in Stackoverflow: https://stackoverflow.com/questions/66708297/unable-to-run-dotnetprojects-wpftoolkit

In my opinion this project is not easy to start with, and there is not too much information about it.

Thank you

**Comment by jogibear9988** [comment]
Yes to it would be nice to have an howto.

Maybe you have time to add one and create a pull request?

But also, your issue belongs to another repo: https://github.com/dotnetprojects/WpfExtendedToolkit
