### ISSUE TITLE
AutoCompleteBox- SearchText cannot be bound to, any particular reason?

### ISSUE THREAD

**Issue by PandaWood** [dotnetprojects/WpfToolkit#60]
This could be my WPF knowledge, but I need to get the `SearchText` property of the auto complete but as far as I can tell, it's not possible by design?

Because there's no accessible setter, I can't even bind to SearchText `OneWay` (which would preserve it's readonly status) - it doesn't compile.

BTW my use case is if what they're searching for is not found, I grab the SearchText and allow them to create a new item...

`SearchText="{Binding ActivitySearchText, Mode=OneWay}"`

**Comment by andySF** [comment]
Hi, please use `SelectionBoxItem="{Binding ActivityModel, Mode=OneWay}"`.

**Comment by PandaWood** [comment]
Hey, sorry I couldn't make any sense of your answer.
I can't see any property called `SelectionBoxItem` to bind to
Here's my control definition, just for clarity

Binding to `Text` just doesn't work, not sure what's going on there, I presume this is by design
And binding to `SearchText` won't compile
So confused as to what anyone would do to make a change to the text of this control

```
<toolkit:AutoCompleteBox
ItemsSource="{Binding ActivityList}"
SelectedItem="{Binding SelectedActivity, Mode=TwoWay}"
Placeholder="Search..."
ItemFilter="{Binding ActivityFilter}"
IsEnabled="{Binding NoNewActivityRequested}"
>
```

**Comment by PandaWood** [comment]
OK I figured this out after looking at more examples...
You have to explicitly bind `Text` property as `TwoWay` .

I was assuming, from experience with a TextBox, that the dependency property defaults to TwoWay binding, but the AutoComplete textbox does not.

**Comment by PandaWood** [comment]
BTW binding TwoWay was not a great answer to my problem. 
I now have the side effect of not populating the SelectedItem. It simply leaves the text you typed in and basically doesn't work at all.
