### ISSUE TITLE
Why is this package not on Nuget?

### ISSUE THREAD

**Issue by Bounder** [dotnetprojects/WpfToolkit#9]
You should publish this package on Nuget. I think it's really cool you picked up development on the MS wpftoolkit! Keep up the great work!

**Comment by westfin** [comment]
Hello, why if install the assembly from nuget version is 5.0.43.0, but if build assembly from source code version 3.5.40128.1?

**Comment by jogibear9988** [comment]
The Version is patched into the source files via appveyor!

i never updated them
